version: '2.4'

services:
  mongo:
    image: mongo:latest
    container_name: falatu_mongo
    ports:
      - '27017:27017'
    volumes:
      - falatu_mongo_data:/data/db
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '8055:8055'
    volumes:
      - falatu_localstack_data:/tmp/localstack
      - ./scripts:/docker-entrypoint-initaws.d
      - type: bind
        source: ./../.env
        target: /.env
    environment:
      - SERVICES=s3
      - PORT_WEB_UI=8055
      - EDGE_PORT=4566

volumes:
  falatu_mongo_data:
  falatu_localstack_data:
